#!/usr/bin/env python3
"""
Generate packaging/ORG_CARD.md from the repo root README.md.

README.md (the full custom HTML/CSS "hero card" design) is the canonical
source for the TI EdgeAI Model Hub's catalog content: overview, use cases,
license summary, compilation tools, quick start, supported hardware, model
catalog, and resource links. This script parses those sections out of
README.md's HTML and re-renders them as plain Markdown, so ORG_CARD.md never
has to be hand-edited/duplicated separately.

Why two files instead of one: HF's organization-card renderer strips <style>
blocks and custom CSS (the same sanitization GitHub applies to READMEs), so
README.md's visual design can't survive there — plain Markdown is the only
format that renders reliably on the org profile page. ORG_CARD.md is pushed
to the TIEdgeAI/README HF Space via:

    python packaging/upload_to_hf.py --org-card --org-card-source packaging/ORG_CARD.md

The Model Catalog's "Docs" links are rewritten from local repo-relative
folder paths (e.g. "models/vision/classification/ResNet/") to the model's
actual HF repo URL, looked up from MODEL_REGISTRY in upload_to_hf.py.

Usage:
    # Regenerate packaging/ORG_CARD.md from README.md
    python packaging/generate_org_card.py

    # Preview without writing
    python packaging/generate_org_card.py --print

    # CI-style check: fail if ORG_CARD.md is stale (doesn't write)
    python packaging/generate_org_card.py --check
"""

import argparse
import html
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from typing import Optional


# ── Paths ──────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / 'README.md'
ORG_CARD_PATH = REPO_ROOT / 'packaging' / 'ORG_CARD.md'

# Relative to packaging/ORG_CARD.md — resolved by upload_to_hf.py's
# localize_org_card_assets() against REPO_ROOT regardless of source location.
LOGO_REF = '../docs/assets/TXN-Logo.png'

ORG_CARD_FRONT_MATTER = (
    "---\n"
    "title: TIEdgeAI\n"
    "emoji: 🤖\n"
    "colorFrom: red\n"
    "colorTo: gray\n"
    "sdk: static\n"
    "pinned: false\n"
    "---\n"
)

GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED by packaging/generate_org_card.py from README.md — "
    "do not edit by hand. Edit README.md and re-run the generator instead. -->"
)


# ── Inline HTML → Markdown ──────────────────────────────────────────────────

class _InlineMarkdownConverter(HTMLParser):
    """
    Convert a small, known-safe subset of inline HTML (as used throughout
    README.md's card bodies) to Markdown: <a>, <strong>/<b>, <em>/<i>,
    <code>, <br>. Any other tag is dropped but its text content is kept.
    """

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self._out: list[str] = []
        self._href_stack: list[str] = []

    def handle_starttag(self, tag, attrs):
        if tag == 'a':
            href = dict(attrs).get('href', '')
            self._href_stack.append(href)
            self._out.append('[')
        elif tag in ('strong', 'b'):
            self._out.append('**')
        elif tag in ('em', 'i'):
            self._out.append('_')
        elif tag == 'code':
            self._out.append('`')
        elif tag == 'br':
            self._out.append(' ')

    def handle_endtag(self, tag):
        if tag == 'a' and self._href_stack:
            href = self._href_stack.pop()
            self._out.append(f']({href})')
        elif tag in ('strong', 'b'):
            self._out.append('**')
        elif tag in ('em', 'i'):
            self._out.append('_')
        elif tag == 'code':
            self._out.append('`')

    def handle_data(self, data):
        self._out.append(data)

    def markdown(self) -> str:
        return ''.join(self._out)


def inline_to_markdown(fragment: str) -> str:
    """Convert an inner-HTML fragment to inline Markdown, collapsing whitespace."""
    conv = _InlineMarkdownConverter()
    conv.feed(fragment)
    conv.close()
    return re.sub(r'\s+', ' ', conv.markdown()).strip()


# ── Balanced <div> extraction ───────────────────────────────────────────────
#
# Several cards contain nested <div> grids (uc-grid, tool-grid, hw-list,
# res-grid), so a naive ".*?</div>" regex would stop at the first nested
# closing tag instead of the card's own. These helpers track nesting depth
# to find the real matching close tag instead.

_DIV_TOKEN_RE = re.compile(r'<div\b|</div>')


def extract_div_block(text: str, start_idx: int) -> tuple[str, int]:
    """
    Given the index just after an already-consumed '<div ...>' opening tag,
    return (inner_html, index_just_after_the_matching_closing_tag).
    """
    depth = 1
    for m in _DIV_TOKEN_RE.finditer(text, start_idx):
        if m.group() == '<div':
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                return text[start_idx:m.start()], m.end()
    raise ValueError("Unbalanced <div> tags while scanning README.md")


_CARD_OPEN_RE = re.compile(r'<div class="card"[^>]*>')
_H2_RE = re.compile(r'<h2>(.*?)</h2>', re.S)


def iter_cards(text: str):
    """Yield (heading_text, inner_html) for every top-level <div class="card">."""
    for m in _CARD_OPEN_RE.finditer(text):
        inner, _ = extract_div_block(text, m.end())
        h2 = _H2_RE.search(inner)
        heading = html.unescape(re.sub(r'<[^>]+>', '', h2.group(1))).strip() if h2 else None
        yield heading, inner


def extract_named_div(text: str, class_name: str) -> str:
    """Return the inner HTML of the first <div class="{class_name}">...</div>."""
    m = re.search(r'<div class="' + re.escape(class_name) + r'"[^>]*>', text)
    if not m:
        raise ValueError(f'generate_org_card.py: could not find <div class="{class_name}"> in README.md')
    inner, _ = extract_div_block(text, m.end())
    return inner


def _extract(pattern: str, text: str) -> str:
    m = re.search(pattern, text, re.S)
    if not m:
        raise ValueError(f"generate_org_card.py: pattern not found in README.md: {pattern[:60]}")
    return m.group(1)


# ── MODEL_REGISTRY lookup (for Model Catalog "Docs" links) ─────────────────

def load_dir_to_repo() -> dict[str, str]:
    """Map each registered model's local directory to its HF repo_id."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from upload_to_hf import MODEL_REGISTRY  # local import: avoid module cost when unused
    return {info['dir']: info['repo_id'] for info in MODEL_REGISTRY.values()}


# ── Per-card renderers ───────────────────────────────────────────────────────

def render_overview(inner: str) -> str:
    para = inline_to_markdown(_extract(r'<p>\s*(.*?)\s*</p>', inner))
    items = re.findall(r'<li>(.*?)</li>', inner, re.S)
    bullets = '\n'.join(f'- {inline_to_markdown(i)}' for i in items)
    return f"{para}\n\n{bullets}"


def render_use_cases(inner: str) -> str:
    items = re.findall(r'<h3>(.*?)</h3>', inner, re.S)
    return ' · '.join(inline_to_markdown(i) for i in items)


def render_license_summary(inner: str) -> str:
    intro = inline_to_markdown(_extract(r'<p>(.*?)</p>', inner))

    lic_matches = re.findall(r'<a([^>]*class="lic[^"]*"[^>]*)>(.*?)</a>', inner, re.S)
    lic_entries = []
    for attrs, text in lic_matches:
        href_m = re.search(r'href="([^"]+)"', attrs)
        href = href_m.group(1) if href_m else '#'
        lic_entries.append(f"**[{inline_to_markdown(text)}]({href})**")
    lic_line = ' · '.join(lic_entries)

    disclaimer_m = re.search(r'<div class="disclaimer">\s*(.*?)\s*</div>', inner, re.S)
    disclaimer = inline_to_markdown(disclaimer_m.group(1)) if disclaimer_m else ''

    paragraphs = [intro]
    if lic_line:
        paragraphs.append(lic_line)
    if disclaimer:
        paragraphs.append(f"> {disclaimer}")
    return "\n\n".join(paragraphs)


def render_compilation(inner: str) -> str:
    cards = re.findall(r'<div class="tool-card">\s*(.*?)\s*</div>', inner, re.S)
    rows = []
    for card in cards:
        h3 = _extract(r'<h3>(.*?)</h3>', card)
        badge_m = re.search(r'<span[^>]*class="tool-badge"[^>]*>(.*?)</span>', h3, re.S)
        badge = inline_to_markdown(badge_m.group(1)) if badge_m else None
        name_html = re.sub(r'<span[^>]*class="tool-badge"[^>]*>.*?</span>', '', h3, flags=re.S)
        name = inline_to_markdown(name_html)
        desc = inline_to_markdown(_extract(r'<p>(.*?)</p>', card))
        label = f"**{name}**" + (f" ({badge.lower()})" if badge else "")
        rows.append(f"| {label} | {desc} |")
    return "| Tool | Description |\n|------|-------------|\n" + "\n".join(rows)


def render_quick_start(inner: str) -> str:
    steps = re.findall(r'<p><strong>(.*?)</strong></p>\s*<pre><code>(.*?)</code></pre>', inner, re.S)
    if not steps:
        raise ValueError("generate_org_card.py: no Quick Start steps found in README.md")
    lines = ["```bash"]
    for title, code in steps:
        lines.append(f"# {inline_to_markdown(title)}")
        lines.append(html.unescape(code).strip())
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("```")
    return "\n".join(lines)


def render_hardware(inner: str) -> str:
    intro = inline_to_markdown(_extract(r'<p>\s*(.*?)\s*</p>', inner))
    items = re.findall(r'<div class="hw-item">\s*(.*?)\s*</div>', inner, re.S)
    rows = []
    for item in items:
        name = inline_to_markdown(_extract(r'<strong>(.*?)</strong>', item))
        # Greedy: hw-aliases spans nest hw-sep spans inside them, so a non-greedy
        # match would stop at the first (inner) </span> instead of the real one.
        # Each hw-item has exactly one hw-aliases span, so grabbing up to the
        # last </span> in `item` is safe and correct.
        aliases_m = re.search(r'<span class="hw-aliases">(.*)</span>', item, re.S)
        if aliases_m:
            raw = re.sub(r'<span class="hw-sep">.*?</span>', '·', aliases_m.group(1), flags=re.S)
            aliases = inline_to_markdown(raw)
        else:
            aliases = '—'
        rows.append(f"| **{name}** | {aliases} |")
    table = "| Device | Aliases |\n|--------|---------|\n" + "\n".join(rows)
    return f"{intro}\n\n{table}"


def render_model_catalog(inner: str, dir_to_repo: dict[str, str]) -> str:
    headers = [inline_to_markdown(h) for h in re.findall(r'<th>(.*?)</th>', inner, re.S)]
    headers = ['Repo' if h == 'Docs' else h for h in headers]

    tbody = _extract(r'<tbody>(.*?)</tbody>', inner)
    rows_html = re.findall(r'<tr>\s*(.*?)\s*</tr>', tbody, re.S)

    md_rows = []
    for row in rows_html:
        cells = re.findall(r'<td>(.*?)</td>', row, re.S)
        rendered = []
        for i, cell in enumerate(cells):
            if i == len(cells) - 1:
                href_m = re.search(r'href="([^"]+)"', cell)
                local_dir = href_m.group(1).rstrip('/') if href_m else None
                repo_id = dir_to_repo.get(local_dir) if local_dir else None
                if repo_id:
                    rendered.append(f"[View](https://huggingface.co/{repo_id})")
                else:
                    print(f"  Warning: no MODEL_REGISTRY entry for catalog link '{local_dir}' "
                          "— leaving link as originally written.")
                    rendered.append(inline_to_markdown(cell))
            else:
                rendered.append(inline_to_markdown(cell))
        md_rows.append('| ' + ' | '.join(rendered) + ' |')

    header_line = '| ' + ' | '.join(headers) + ' |'
    sep_line = '|' + '|'.join('---' for _ in headers) + '|'
    return '\n'.join([header_line, sep_line] + md_rows)


def render_resources(inner: str) -> str:
    cards = re.findall(r'<div class="res-card">\s*(.*?)\s*</div>', inner, re.S)
    lines = []
    for card in cards:
        category = inline_to_markdown(_extract(r'<h3>(.*?)</h3>', card))
        links = re.findall(r'<a\s+href="([^"]+)"[^>]*>(.*?)</a>', card, re.S)
        link_md = ' · '.join(f'[{inline_to_markdown(t)}]({href})' for href, t in links)
        lines.append(f"- **{category}:** {link_md}")
    return '\n'.join(lines)


SECTION_RENDERERS = [
    ("Overview", render_overview, ()),
    ("Use Cases", render_use_cases, ()),
    ("License Summary", render_license_summary, ()),
    ("Compilation & Deployment", render_compilation, ()),
    ("Quick Start", render_quick_start, ()),
    ("Supported Hardware", render_hardware, ()),
    ("Model Catalog", render_model_catalog, ('dir_to_repo',)),
    ("Resources & Links", render_resources, ()),
]


# ── Footer ───────────────────────────────────────────────────────────────────

def extract_footer_line(text: str) -> str:
    m = re.search(r'<div class="footer">\s*<p>(.*?)</p>', text, re.S)
    if not m:
        raise ValueError('generate_org_card.py: could not find <div class="footer"> in README.md')
    return inline_to_markdown(m.group(1))


# ── Assembly ─────────────────────────────────────────────────────────────────

def build_markdown(readme_html: str) -> str:
    cards = dict(iter_cards(readme_html))

    hero_inner = extract_named_div(readme_html, 'hero')
    hero_title = inline_to_markdown(_extract(r'<h1[^>]*>(.*?)</h1>', hero_inner))
    hero_tagline = inline_to_markdown(_extract(r'<p[^>]*>(.*?)</p>', hero_inner))
    footer_line = extract_footer_line(readme_html)

    dir_to_repo = load_dir_to_repo()

    parts = [
        ORG_CARD_FRONT_MATTER.rstrip('\n'),
        "",
        GENERATED_NOTICE,
        "",
        '<div align="center">',
        "",
        f'<img src="{LOGO_REF}" alt="Texas Instruments" width="72" height="72" />',
        "",
        f"# {hero_title}",
        "",
        f"**{hero_tagline}**",
        "",
        "</div>",
        "",
        "---",
    ]

    for heading, renderer, extra_kwargs in SECTION_RENDERERS:
        inner = cards.get(heading)
        if inner is None:
            print(f"  Warning: card '{heading}' not found in README.md — skipping that section.")
            continue
        kwargs = {name: dir_to_repo for name in extra_kwargs}
        body = renderer(inner, **kwargs)
        parts += ["", f"## {heading}", "", body, "", "---"]

    parts += [
        "",
        '<div align="center">',
        "",
        f"**{footer_line}**",
        "",
        "</div>",
        "",
    ]

    return '\n'.join(parts)


# ── CLI ───────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description='Generate packaging/ORG_CARD.md from the repo root README.md',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        '--readme', default=str(README_PATH), metavar='PATH',
        help='Source README.md to read (default: repo root README.md)',
    )
    p.add_argument(
        '--out', default=str(ORG_CARD_PATH), metavar='PATH',
        help='Output path (default: packaging/ORG_CARD.md)',
    )
    p.add_argument(
        '--print', dest='print_only', action='store_true',
        help='Print the generated content to stdout instead of writing it',
    )
    p.add_argument(
        '--check', action='store_true',
        help='Exit 1 if the output file is missing or out of date, without writing (for CI)',
    )
    return p


def main() -> None:
    args = build_parser().parse_args()

    readme_path = Path(args.readme)
    if not readme_path.is_file():
        sys.exit(f"Error: README source not found: {readme_path}")

    readme_html = readme_path.read_text(encoding='utf-8')

    try:
        generated = build_markdown(readme_html)
    except ValueError as exc:
        sys.exit(f"Error: {exc}")

    if args.print_only:
        print(generated)
        return

    out_path = Path(args.out)

    if args.check:
        current = out_path.read_text(encoding='utf-8') if out_path.is_file() else None
        if current == generated:
            print(f"OK: {out_path} is up to date with {readme_path}.")
            return
        sys.exit(f"STALE: {out_path} does not match {readme_path}. Run without --check to regenerate.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generated, encoding='utf-8')
    print(f"Wrote {out_path} ({len(generated)} bytes) from {readme_path}.")


if __name__ == '__main__':
    main()
