#!/usr/bin/env python3
"""
Generate packaging/ORG_CARD.md from the repo root README.md.

README.md (the full custom HTML/CSS "hero card" design) is the canonical
source for the TI EdgeAI Model Hub's catalog content: overview, use cases,
license summary, compilation tools, quick start, supported hardware, model
catalog, and resource links. This script parses those sections out of
README.md's HTML and re-renders them as plain Markdown, so ORG_CARD.md never
has to be hand-edited/duplicated separately.

Why two files instead of one: HF's organization-card renderer strips <style>
blocks and custom CSS (the same sanitization GitHub applies to READMEs), so
README.md's visual design can't survive there — plain Markdown is the only
format that renders reliably on the org profile page. ORG_CARD.md is pushed
to the TIEdgeAI/README HF Space via:

    python packaging/upload_to_hf.py --org-card --org-card-source packaging/ORG_CARD.md

The Model Catalog's "Docs" links are rewritten from local repo-relative
folder paths (e.g. "models/vision/classification/ResNet/") to the model's
actual HF repo URL, looked up from MODEL_REGISTRY in upload_to_hf.py.

Parsing approach: README.md is parsed into a small generic HTML tree (see
_Node/_TreeBuilder below) rather than matched with per-section regexes, so
card renderers query by tag/class instead of assuming an exact HTML shape.
This keeps the script tolerant of routine README edits (extra wrapper divs,
whitespace changes, a name moving in or out of a <strong>, etc.) — only a
genuine removal of a card/section should require touching this script.

Usage:
    # Regenerate packaging/ORG_CARD.md from README.md
    python packaging/generate_org_card.py

    # Preview without writing
    python packaging/generate_org_card.py --print

    # CI-style check: fail if ORG_CARD.md is stale (doesn't write)
    python packaging/generate_org_card.py --check
"""

import argparse
import re
import sys
from html.parser import HTMLParser
from pathlib import Path


# ── Paths ──────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / 'README.md'
ORG_CARD_PATH = REPO_ROOT / 'packaging' / 'ORG_CARD.md'

# Relative to packaging/ORG_CARD.md — resolved by upload_to_hf.py's
# localize_org_card_assets() against REPO_ROOT regardless of source location.
LOGO_REF = '../docs/assets/TXN-Logo.png'

ORG_CARD_FRONT_MATTER = (
    "---\n"
    "title: TIEdgeAI\n"
    "emoji: 🤖\n"
    "colorFrom: red\n"
    "colorTo: gray\n"
    "sdk: static\n"
    "pinned: false\n"
    "---\n"
)

GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED by packaging/generate_org_card.py from README.md — "
    "do not edit by hand. Edit README.md and re-run the generator instead. -->"
)


# ── Generic HTML tree ────────────────────────────────────────────────────────
#
# A minimal DOM: each element is a _Node with a tag, attrs, and children
# (a mix of _Node and plain text strings). Built with a stack-based
# HTMLParser subclass so nesting (however deep — grids inside cards inside
# the page) is tracked correctly, unlike a regex which has no concept of
# "the matching closing tag."

_VOID_TAGS = {
    'area', 'base', 'br', 'col', 'embed', 'hr', 'img',
    'input', 'link', 'meta', 'param', 'source', 'track', 'wbr',
}

_INLINE_MARKUP = {
    'a': lambda node: f'[{node.markdown()}]({node.attrs.get("href", "")})',
    'strong': lambda node: f'**{node.markdown()}**',
    'b': lambda node: f'**{node.markdown()}**',
    'em': lambda node: f'_{node.markdown()}_',
    'i': lambda node: f'_{node.markdown()}_',
    'code': lambda node: f'`{node.markdown()}`',
    'br': lambda node: ' ',
}


class _Node:
    def __init__(self, tag, attrs=None, parent=None):
        self.tag = tag
        self.attrs = dict(attrs or ())
        self.children = []  # list of _Node | str
        self.parent = parent

    @property
    def classes(self):
        return (self.attrs.get('class') or '').split()

    def has_class(self, name):
        return name in self.classes

    def next_element_sibling(self):
        """The next _Node sibling (skipping text nodes), or None."""
        if self.parent is None:
            return None
        siblings = self.parent.children
        idx = siblings.index(self)
        for sib in siblings[idx + 1:]:
            if isinstance(sib, _Node):
                return sib
        return None

    def descendants(self):
        """Yield all descendant _Nodes, depth-first, document order."""
        for c in self.children:
            if isinstance(c, _Node):
                yield c
                yield from c.descendants()

    def find(self, tag=None, class_=None):
        for n in self.descendants():
            if (tag is None or n.tag == tag) and (class_ is None or n.has_class(class_)):
                return n
        return None

    def find_all(self, tag=None, class_=None):
        return [
            n for n in self.descendants()
            if (tag is None or n.tag == tag) and (class_ is None or n.has_class(class_))
        ]

    def text(self):
        """Plain-text content, recursive, whitespace-collapsed. Drops all markup."""
        parts = [c if isinstance(c, str) else c.text() for c in self.children]
        return re.sub(r'\s+', ' ', ''.join(parts)).strip()

    def raw_text(self):
        """Plain-text content, recursive, whitespace preserved verbatim (for <pre>/<code>)."""
        parts = [c if isinstance(c, str) else c.raw_text() for c in self.children]
        return ''.join(parts)

    def text_before(self, tag):
        """Plain text of children up to (not including) the first child with `tag`."""
        parts = []
        for c in self.children:
            if isinstance(c, _Node) and c.tag == tag:
                break
            parts.append(c if isinstance(c, str) else c.text())
        return re.sub(r'\s+', ' ', ''.join(parts)).strip()

    def markdown(self, skip=None):
        """
        Inline Markdown for this node's children: <a>/<strong>/<b>/<em>/<i>/
        <code>/<br> are converted, any other tag is dropped but its own
        text/markdown content is kept. `skip` is an optional set of child
        _Node identities to omit entirely (e.g. a badge nested in a heading).
        """
        skip = skip or ()
        out = []
        for c in self.children:
            if isinstance(c, str):
                out.append(c)
            elif c in skip:
                continue
            elif c.tag in _INLINE_MARKUP:
                out.append(_INLINE_MARKUP[c.tag](c))
            else:
                out.append(c.markdown())
        return ''.join(out)

    def markdown_stripped(self, skip=None):
        return re.sub(r'\s+', ' ', self.markdown(skip)).strip()


class _TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = _Node(None)
        self._stack = [self.root]

    def handle_starttag(self, tag, attrs):
        parent = self._stack[-1]
        node = _Node(tag, attrs, parent=parent)
        parent.children.append(node)
        if tag not in _VOID_TAGS:
            self._stack.append(node)

    def handle_endtag(self, tag):
        for i in range(len(self._stack) - 1, 0, -1):
            if self._stack[i].tag == tag:
                del self._stack[i:]
                return
        # Unmatched close tag — ignore rather than raising, since README.md
        # is well-formed HTML in practice and a stray tag shouldn't be fatal.

    def handle_data(self, data):
        if data:
            self._stack[-1].children.append(data)


def parse_html(text: str) -> _Node:
    builder = _TreeBuilder()
    builder.feed(text)
    builder.close()
    return builder.root


def _require(node, what: str) -> _Node:
    if node is None:
        raise ValueError(f'generate_org_card.py: could not find {what} in README.md')
    return node


# ── MODEL_REGISTRY lookup (for Model Catalog "Docs" links) ─────────────────

def load_dir_to_repo() -> dict[str, str]:
    """Map each registered model's local directory to its HF repo_id."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from upload_to_hf import MODEL_REGISTRY  # local import: avoid module cost when unused
    return {info['dir']: info['repo_id'] for info in MODEL_REGISTRY.values()}


# ── Per-card renderers ───────────────────────────────────────────────────────
#
# Each renderer receives the card's _Node and queries it by tag/class rather
# than assuming a fixed HTML shape, so routine README edits (an extra wrapper
# div, a name moving in or out of a <strong>, whitespace changes) shouldn't
# require changes here.

def render_overview(card: _Node) -> str:
    p = card.find(tag='p')
    para = p.markdown_stripped() if p else ''
    items = card.find_all(tag='li')
    bullets = '\n'.join(f'- {li.markdown_stripped()}' for li in items)
    return f"{para}\n\n{bullets}"


def render_use_cases(card: _Node) -> str:
    items = card.find_all(tag='h3')
    return ' · '.join(h.markdown_stripped() for h in items)


def render_license_summary(card: _Node) -> str:
    p = card.find(tag='p')
    intro = p.markdown_stripped() if p else ''

    lic_entries = []
    for a in card.find_all(tag='a'):
        if a.has_class('lic'):
            href = a.attrs.get('href', '#')
            lic_entries.append(f"**[{a.markdown_stripped()}]({href})**")
    lic_line = ' · '.join(lic_entries)

    disclaimer_div = card.find(tag='div', class_='disclaimer')
    disclaimer = disclaimer_div.markdown_stripped() if disclaimer_div else ''

    paragraphs = [intro]
    if lic_line:
        paragraphs.append(lic_line)
    if disclaimer:
        paragraphs.append(f"> {disclaimer}")
    return "\n\n".join(paragraphs)


def render_compilation(card: _Node) -> str:
    rows = []
    for tool_card in card.find_all(tag='div', class_='tool-card'):
        h3 = _require(tool_card.find(tag='h3'), '<h3> inside a "tool-card"')
        p = tool_card.find(tag='p')
        badge_node = h3.find(tag='span', class_='tool-badge')
        badge = badge_node.markdown_stripped() if badge_node else None
        name = h3.markdown_stripped(skip={badge_node} if badge_node else None)
        desc = p.markdown_stripped() if p else ''
        label = f"**{name}**" + (f" ({badge.lower()})" if badge else "")
        rows.append(f"| {label} | {desc} |")
    return "| Tool | Description |\n|------|-------------|\n" + "\n".join(rows)


def render_quick_start(card: _Node) -> str:
    steps = []
    for p in card.find_all(tag='p'):
        nxt = p.next_element_sibling()
        if nxt is None or nxt.tag != 'pre':
            continue
        strong = p.find(tag='strong') or p.find(tag='b')
        title = strong.markdown_stripped() if strong else p.markdown_stripped()
        code_node = nxt.find(tag='code')
        code_text = (code_node or nxt).raw_text()
        steps.append((title, code_text))

    if not steps:
        raise ValueError("generate_org_card.py: no Quick Start steps found in README.md")

    lines = ["```bash"]
    for title, code in steps:
        lines.append(f"# {title}")
        lines.append(code.strip())
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("```")
    return "\n".join(lines)


def render_hardware(card: _Node) -> str:
    p = card.find(tag='p')
    intro = p.markdown_stripped() if p else ''

    rows = []
    for item in card.find_all(tag='div', class_='hw-item'):
        # The device family name is whatever text/​<strong> precedes the
        # first <a>; aliases are simply every <a> in the item, wherever
        # nested. This works whether the name is bare text or wrapped in
        # <strong>, and whether aliases sit in a dedicated wrapper span or not.
        name = item.text_before('a')
        alias_links = item.find_all(tag='a')
        aliases = ' · '.join(
            f'[{a.markdown_stripped()}]({a.attrs.get("href", "")})' for a in alias_links
        ) if alias_links else '—'
        rows.append(f"| **{name}** | {aliases} |")

    table = "| Device | Aliases |\n|--------|---------|\n" + "\n".join(rows)
    return f"{intro}\n\n{table}"


def render_model_catalog(card: _Node, dir_to_repo: dict[str, str]) -> str:
    thead = card.find(tag='thead')
    headers = [th.markdown_stripped() for th in thead.find_all(tag='th')] if thead else []
    docs_idx = next((i for i, h in enumerate(headers) if h.strip().lower() == 'docs'), None)
    if docs_idx is not None:
        headers[docs_idx] = 'Repo'

    tbody = card.find(tag='tbody')
    md_rows = []
    for tr in (tbody.find_all(tag='tr') if tbody else []):
        cells = tr.find_all(tag='td')
        rendered = []
        for i, cell in enumerate(cells):
            if i == docs_idx:
                a = cell.find(tag='a')
                href = a.attrs.get('href') if a else None
                local_dir = href.rstrip('/') if href else None
                repo_id = dir_to_repo.get(local_dir) if local_dir else None
                if repo_id:
                    rendered.append(f"[View](https://huggingface.co/{repo_id})")
                else:
                    print(f"  Warning: no MODEL_REGISTRY entry for catalog link '{local_dir}' "
                          "— leaving link as originally written.")
                    rendered.append(cell.markdown_stripped())
            else:
                rendered.append(cell.markdown_stripped())
        md_rows.append('| ' + ' | '.join(rendered) + ' |')

    header_line = '| ' + ' | '.join(headers) + ' |'
    sep_line = '|' + '|'.join('---' for _ in headers) + '|'
    return '\n'.join([header_line, sep_line] + md_rows)


def render_resources(card: _Node) -> str:
    lines = []
    for res_card in card.find_all(tag='div', class_='res-card'):
        h3 = res_card.find(tag='h3')
        category = h3.markdown_stripped() if h3 else ''
        links = res_card.find_all(tag='a')
        link_md = ' · '.join(f'[{a.markdown_stripped()}]({a.attrs.get("href", "")})' for a in links)
        lines.append(f"- **{category}:** {link_md}")
    return '\n'.join(lines)


SECTION_RENDERERS = [
    ("Overview", render_overview, ()),
    ("Use Cases", render_use_cases, ()),
    ("License Summary", render_license_summary, ()),
    ("Compilation & Deployment", render_compilation, ()),
    ("Quick Start", render_quick_start, ()),
    ("Supported Hardware", render_hardware, ()),
    ("Model Catalog", render_model_catalog, ('dir_to_repo',)),
    ("Resources & Links", render_resources, ()),
]


# ── Card discovery ───────────────────────────────────────────────────────────

def iter_cards(root: _Node):
    """Yield (heading_text, card_node) for every <div class="card"> in the document."""
    for div in root.find_all(tag='div', class_='card'):
        h2 = div.find(tag='h2')
        heading = h2.text() if h2 else None
        yield heading, div


# ── Assembly ─────────────────────────────────────────────────────────────────

def build_markdown(readme_html: str) -> str:
    root = parse_html(readme_html)
    cards = dict(iter_cards(root))

    hero = _require(root.find(tag='div', class_='hero'), '<div class="hero">')
    hero_title = _require(hero.find(tag='h1'), '<h1> inside the hero').markdown_stripped()
    hero_tagline = _require(hero.find(tag='p'), '<p> inside the hero').markdown_stripped()

    footer = _require(root.find(tag='div', class_='footer'), '<div class="footer">')
    footer_line = _require(footer.find(tag='p'), '<p> inside the footer').markdown_stripped()

    dir_to_repo = load_dir_to_repo()

    parts = [
        ORG_CARD_FRONT_MATTER.rstrip('\n'),
        "",
        GENERATED_NOTICE,
        "",
        '<div align="center">',
        "",
        f'<img src="{LOGO_REF}" alt="Texas Instruments" width="72" height="72" />',
        "",
        f"# {hero_title}",
        "",
        f"**{hero_tagline}**",
        "",
        "</div>",
        "",
        "---",
    ]

    for heading, renderer, extra_kwargs in SECTION_RENDERERS:
        card = cards.get(heading)
        if card is None:
            print(f"  Warning: card '{heading}' not found in README.md — skipping that section.")
            continue
        kwargs = {name: dir_to_repo for name in extra_kwargs}
        body = renderer(card, **kwargs)
        parts += ["", f"## {heading}", "", body, "", "---"]

    parts += [
        "",
        '<div align="center">',
        "",
        f"**{footer_line}**",
        "",
        "</div>",
        "",
    ]

    return '\n'.join(parts)


# ── CLI ───────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description='Generate packaging/ORG_CARD.md from the repo root README.md',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        '--readme', default=str(README_PATH), metavar='PATH',
        help='Source README.md to read (default: repo root README.md)',
    )
    p.add_argument(
        '--out', default=str(ORG_CARD_PATH), metavar='PATH',
        help='Output path (default: packaging/ORG_CARD.md)',
    )
    p.add_argument(
        '--print', dest='print_only', action='store_true',
        help='Print the generated content to stdout instead of writing it',
    )
    p.add_argument(
        '--check', action='store_true',
        help='Exit 1 if the output file is missing or out of date, without writing (for CI)',
    )
    return p


def main() -> None:
    args = build_parser().parse_args()

    readme_path = Path(args.readme)
    if not readme_path.is_file():
        sys.exit(f"Error: README source not found: {readme_path}")

    readme_html = readme_path.read_text(encoding='utf-8')

    try:
        generated = build_markdown(readme_html)
    except ValueError as exc:
        sys.exit(f"Error: {exc}")

    if args.print_only:
        print(generated)
        return

    out_path = Path(args.out)

    if args.check:
        current = out_path.read_text(encoding='utf-8') if out_path.is_file() else None
        if current == generated:
            print(f"OK: {out_path} is up to date with {readme_path}.")
            return
        sys.exit(f"STALE: {out_path} does not match {readme_path}. Run without --check to regenerate.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generated, encoding='utf-8')
    print(f"Wrote {out_path} ({len(generated)} bytes) from {readme_path}.")


if __name__ == '__main__':
    main()
